(function(t,n,s){try{n._plt=n._plt||(s&&s.timeOrigin?s.timeOrigin+s.now():Date.now()-60);var o,i,a,c,l,d,r=t.head||t.getElementsByTagName("head")[0];if(!r)return;!0&&(c="https://cdn.converteai.net/b5e8472d-3421-4675-a219-1ae1b636b21f/6a14ccf1fd96a937a8912e1a/main.m3u8",t.querySelector('link[rel="preload"][href="'+c+'"]')||(o=t.createElement("link"),o.rel="preload",o.href=c,o.setAttribute("as","fetch"),o.setAttribute("crossorigin","anonymous"),r.appendChild(o)));for(l=["https://cdn.converteai.net","https://images.converteai.net","https://license.vturb.com"],i=0;i<l.length;i++){if(d=l[i],t.querySelector('link[rel="dns-prefetch"][href="'+d+'"]'))continue;a=t.createElement("link"),a.rel="dns-prefetch",a.href=d,r.appendChild(a)}}catch(e){n.console&&n.console.error&&n.console.error("vturb resource preloads injection failed",e)}})(document,window,performance),function(){var t=document.getElementById("vid-6a14ce977bc2268dcbb4c382"),e={elementId:"vid-6a14ce977bc2268dcbb4c382",preloads:{},config:{id:"6a14ce977bc2268dcbb4c382",step:5,config:{callActions:{active:!1,version:1,items:[]},cdn:"cdn.converteai.net",conversion:["sub19","unique_aff_sub5"],embedVersion:"1781210101-dynamodb",fakeBar:{active:!0,alpha:2,height:10,color:"#674EA7"},headlines:{active:!1,items:[]},id:"6a14ce977bc2268dcbb4c382",immersiveMode:{active:!1,disableScrolling:!1,desktop:!1,expandOnPlay:!1,minimizeOnPause:!1,mobile:!1},language:null,minihooks:{active:!1,items:[]},oid:"b5e8472d-3421-4675-a219-1ae1b636b21f",pitchTime:2751,pixels:{active:!0,items:[{id:"6a15a23ad6448eef9de3d325_40843320",type:"custom",dispatchIn:1,dispatchType:"time",customHtml:`PCEtLSBWdHVyYlBsYXkgT25seSAmIFJlc2lsaWVudCBUcmFja2luZyBTY3Jp
cHQgLS0+CjxzY3JpcHQgZGVmZXI+CigoKSA9PiB7CiAgY29uc3QgVFJBQ0tf
RE9NQUlOID0gInFlamR5LnR0cmsuaW8iOwogIGNvbnN0IFNVQklEX0tFWSAg
ICA9ICJydGtjbGlja2lkLXN0b3JlIjsKICBjb25zdCBTVUJJRF9SWCAgICAg
PSAvXltBLVphLXowLTlfLV17MjR9JC87CiAgY29uc3QgTE9DQUxfS0VZICAg
ID0gInRyYWNraW5nUXVldWUiOwoKICAvLyBSZXNvbHZlIHN1YklkIG9uY2UK
ICBsZXQgc3ViSWQ7CiAgKGZ1bmN0aW9uKCkgewogICAgY29uc3QgbSA9IGRv
Y3VtZW50LmNvb2tpZS5tYXRjaChuZXcgUmVnRXhwKCcoPzpefDsgKScgKyBT
VUJJRF9LRVkgKyAnPShbXjtdKiknKSk7CiAgICBpZiAobSkgeyBzdWJJZCA9
IGRlY29kZVVSSUNvbXBvbmVudChtWzFdKTsgcmV0dXJuOyB9CiAgICBmb3Ig
KGNvbnN0IHYgb2YgbmV3IFVSTFNlYXJjaFBhcmFtcyhsb2NhdGlvbi5zZWFy
Y2gpLnZhbHVlcygpKSB7CiAgICAgIGlmIChTVUJJRF9SWC50ZXN0KHYpKSB7
IHN1YklkID0gdjsgYnJlYWs7IH0KICAgIH0KICB9KSgpOwogIGlmICghc3Vi
SWQpIHJldHVybjsKCiAgLy8gUXVldWUgc3RvcmVkIGluIGxvY2FsU3RvcmFn
ZQogIGZ1bmN0aW9uIGdldFF1ZXVlKCkgewogICAgdHJ5IHsgcmV0dXJuIEpT
T04ucGFyc2UobG9jYWxTdG9yYWdlLmdldEl0ZW0oTE9DQUxfS0VZKSkgfHwg
W107IH0KICAgIGNhdGNoIHsgcmV0dXJuIFtdOyB9CiAgfQogIGZ1bmN0aW9u
IHNhdmVRdWV1ZShxKSB7IGxvY2FsU3RvcmFnZS5zZXRJdGVtKExPQ0FMX0tF
WSwgSlNPTi5zdHJpbmdpZnkocSkpOyB9CgogIC8vIEFkZCBldmVudCB0byBx
dWV1ZSB3aXRoIGxvZ2dpbmcKICBmdW5jdGlvbiBlbnF1ZXVlKHR5cGUpIHsK
ICAgIGNvbnNvbGUubG9nKGBbJHt0eXBlfV0gcXVldWVkIGNsaWNraWQ6ICR7
c3ViSWR9YCk7CiAgICBjb25zdCBxdWV1ZSA9IGdldFF1ZXVlKCk7CiAgICBx
dWV1ZS5wdXNoKHsgY2xpY2tpZDogc3ViSWQsIHR5cGUsIHRzOiBEYXRlLm5v
dygpIH0pOwogICAgc2F2ZVF1ZXVlKHF1ZXVlKTsKICB9CgogIC8vIEZsdXNo
IHBlbmRpbmcgZXZlbnRzIHdpdGggZmFsbGJhY2sKICBmdW5jdGlvbiBmbHVz
aCgpIHsKICAgIGxldCBxdWV1ZSA9IGdldFF1ZXVlKCk7CiAgICBpZiAoIXF1
ZXVlLmxlbmd0aCkgcmV0dXJuOwogICAgY29uc3QgcmVtYWluaW5nID0gW107
CiAgICBxdWV1ZS5mb3JFYWNoKGl0ZW0gPT4gewogICAgICBjb25zdCB1cmwg
PSBgaHR0cHM6Ly8ke1RSQUNLX0RPTUFJTn0vcG9zdGJhY2s/Y2xpY2tpZD0k
e2l0ZW0uY2xpY2tpZH0mdHlwZT0ke2l0ZW0udHlwZX1gOwogICAgICBjb25z
b2xlLmxvZyhgWyR7aXRlbS50eXBlfV0gc2VuZGluZyBjbGlja2lkOiAke2l0
ZW0uY2xpY2tpZH1gKTsKICAgICAgbGV0IHNlbnRPSyA9IGZhbHNlOwogICAg
ICBpZiAobmF2aWdhdG9yLnNlbmRCZWFjb24pIHNlbnRPSyA9IG5hdmlnYXRv
ci5zZW5kQmVhY29uKHVybCk7CiAgICAgIGlmICghc2VudE9LICYmIHdpbmRv
dy5mZXRjaCkgewogICAgICAgIGZldGNoKHVybCwgeyBtZXRob2Q6ICdHRVQn
LCBrZWVwYWxpdmU6IHRydWUgfSkKICAgICAgICAgIC50aGVuKCgpID0+IGNv
bnNvbGUubG9nKGBbJHtpdGVtLnR5cGV9XSBmZXRjaCBzdWNjZWVkZWQgZm9y
IGNsaWNraWQ6ICR7aXRlbS5jbGlja2lkfWApKQogICAgICAgICAgLmNhdGNo
KCgpID0+IHsKICAgICAgICAgICAgY29uc29sZS5lcnJvcihgWyR7aXRlbS50
eXBlfV0gZmV0Y2ggZXJyb3IgZm9yIGNsaWNraWQ6ICR7aXRlbS5jbGlja2lk
fWApOwogICAgICAgICAgICByZW1haW5pbmcucHVzaChpdGVtKTsKICAgICAg
ICAgIH0pOwogICAgICB9IGVsc2UgaWYgKCFuYXZpZ2F0b3Iuc2VuZEJlYWNv
bikgewogICAgICAgIGNvbnNvbGUubG9nKGBbJHtpdGVtLnR5cGV9XSB1c2lu
ZyBJbWFnZSBmYWxsYmFjayBmb3IgY2xpY2tpZDogJHtpdGVtLmNsaWNraWR9
YCk7CiAgICAgICAgbmV3IEltYWdlKCkuc3JjID0gdXJsOwogICAgICB9CiAg
ICAgIGlmIChuYXZpZ2F0b3Iuc2VuZEJlYWNvbiAmJiBzZW50T0spIHsKICAg
ICAgICBjb25zb2xlLmxvZyhgWyR7aXRlbS50eXBlfV0gYmVhY29uIHN1Y2Nl
ZWRlZCBmb3IgY2xpY2tpZDogJHtpdGVtLmNsaWNraWR9YCk7CiAgICAgIH0K
ICAgIH0pOwogICAgc2F2ZVF1ZXVlKHJlbWFpbmluZyk7CiAgfQoKICAvLyBP
biBwYWdlIGxvYWQsIGVucXVldWUgYW5kIGZsdXNoIFBsYXkgb25seQogIGVu
cXVldWUoIlBsYXkiKTsKICBmbHVzaCgpOwoKICAvLyBSZXRyeSBwZW5kaW5n
IG9uIHVubG9hZC92aXNpYmlsaXR5IGNoYW5nZQogIHdpbmRvdy5hZGRFdmVu
dExpc3RlbmVyKCd2aXNpYmlsaXR5Y2hhbmdlJywgKCkgPT4gewogICAgaWYg
KGRvY3VtZW50LnZpc2liaWxpdHlTdGF0ZSA9PT0gJ2hpZGRlbicpIGZsdXNo
KCk7CiAgfSk7CiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2JlZm9yZXVu
bG9hZCcsIGZsdXNoKTsKfSkoKTsKPC9zY3JpcHQ+Cg==
`},{id:"6a15a23ad6448eef9de3d326_cba85864",type:"custom",dispatchIn:2751,dispatchType:"time",customHtml:`PCEtLSBWdHVyYlBpdGNoIE9ubHkgJiBSZXNpbGllbnQgVHJhY2tpbmcgU2Ny
aXB0IC0tPgo8c2NyaXB0IGRlZmVyPgooKCkgPT4gewogIGNvbnN0IFRSQUNL
X0RPTUFJTiA9ICJxZWpkeS50dHJrLmlvIjsKICBjb25zdCBTVUJJRF9LRVkg
ICAgPSAicnRrY2xpY2tpZC1zdG9yZSI7CiAgY29uc3QgU1VCSURfUlggICAg
ID0gL15bQS1aYS16MC05Xy1dezI0fSQvOwogIGNvbnN0IExPQ0FMX0tFWSAg
ICA9ICJ0cmFja2luZ1F1ZXVlIjsKCiAgLy8gUmVzb2x2ZSBzdWJJZCBvbmNl
CiAgbGV0IHN1YklkOwogIChmdW5jdGlvbigpIHsKICAgIGNvbnN0IG0gPSBk
b2N1bWVudC5jb29raWUubWF0Y2gobmV3IFJlZ0V4cCgnKD86Xnw7ICknICsg
U1VCSURfS0VZICsgJz0oW147XSopJykpOwogICAgaWYgKG0pIHsgc3ViSWQg
PSBkZWNvZGVVUklDb21wb25lbnQobVsxXSk7IHJldHVybjsgfQogICAgZm9y
IChjb25zdCB2IG9mIG5ldyBVUkxTZWFyY2hQYXJhbXMobG9jYXRpb24uc2Vh
cmNoKS52YWx1ZXMoKSkgewogICAgICBpZiAoU1VCSURfUlgudGVzdCh2KSkg
eyBzdWJJZCA9IHY7IGJyZWFrOyB9CiAgICB9CiAgfSkoKTsKICBpZiAoIXN1
YklkKSByZXR1cm47CgogIC8vIFF1ZXVlIHN0b3JlZCBpbiBsb2NhbFN0b3Jh
Z2UKICBmdW5jdGlvbiBnZXRRdWV1ZSgpIHsKICAgIHRyeSB7IHJldHVybiBK
U09OLnBhcnNlKGxvY2FsU3RvcmFnZS5nZXRJdGVtKExPQ0FMX0tFWSkpIHx8
IFtdOyB9CiAgICBjYXRjaCB7IHJldHVybiBbXTsgfQogIH0KICBmdW5jdGlv
biBzYXZlUXVldWUocSkgeyBsb2NhbFN0b3JhZ2Uuc2V0SXRlbShMT0NBTF9L
RVksIEpTT04uc3RyaW5naWZ5KHEpKTsgfQoKICAvLyBBZGQgZXZlbnQgdG8g
cXVldWUgd2l0aCBsb2dnaW5nCiAgZnVuY3Rpb24gZW5xdWV1ZSh0eXBlKSB7
CiAgICBjb25zb2xlLmxvZyhgWyR7dHlwZX1dIHF1ZXVlZCBjbGlja2lkOiAk
e3N1YklkfWApOwogICAgY29uc3QgcXVldWUgPSBnZXRRdWV1ZSgpOwogICAg
cXVldWUucHVzaCh7IGNsaWNraWQ6IHN1YklkLCB0eXBlLCB0czogRGF0ZS5u
b3coKSB9KTsKICAgIHNhdmVRdWV1ZShxdWV1ZSk7CiAgfQoKICAvLyBGbHVz
aCBwZW5kaW5nIGV2ZW50cyB3aXRoIGZhbGxiYWNrCiAgZnVuY3Rpb24gZmx1
c2goKSB7CiAgICBsZXQgcXVldWUgPSBnZXRRdWV1ZSgpOwogICAgaWYgKCFx
dWV1ZS5sZW5ndGgpIHJldHVybjsKICAgIGNvbnN0IHJlbWFpbmluZyA9IFtd
OwogICAgcXVldWUuZm9yRWFjaChpdGVtID0+IHsKICAgICAgY29uc3QgdXJs
ID0gYGh0dHBzOi8vJHtUUkFDS19ET01BSU59L3Bvc3RiYWNrP2NsaWNraWQ9
JHtpdGVtLmNsaWNraWR9JnR5cGU9JHtpdGVtLnR5cGV9YDsKICAgICAgY29u
c29sZS5sb2coYFske2l0ZW0udHlwZX1dIHNlbmRpbmcgY2xpY2tpZDogJHtp
dGVtLmNsaWNraWR9YCk7CiAgICAgIGxldCBzZW50T0sgPSBmYWxzZTsKICAg
ICAgaWYgKG5hdmlnYXRvci5zZW5kQmVhY29uKSBzZW50T0sgPSBuYXZpZ2F0
b3Iuc2VuZEJlYWNvbih1cmwpOwogICAgICBpZiAoIXNlbnRPSyAmJiB3aW5k
b3cuZmV0Y2gpIHsKICAgICAgICBmZXRjaCh1cmwsIHsgbWV0aG9kOiAnR0VU
Jywga2VlcGFsaXZlOiB0cnVlIH0pCiAgICAgICAgICAudGhlbigoKSA9PiBj
b25zb2xlLmxvZyhgWyR7aXRlbS50eXBlfV0gZmV0Y2ggc3VjY2VlZGVkIGZv
ciBjbGlja2lkOiAke2l0ZW0uY2xpY2tpZH1gKSkKICAgICAgICAgIC5jYXRj
aCgoKSA9PiB7CiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoYFske2l0ZW0u
dHlwZX1dIGZldGNoIGVycm9yIGZvciBjbGlja2lkOiAke2l0ZW0uY2xpY2tp
ZH1gKTsKICAgICAgICAgICAgcmVtYWluaW5nLnB1c2goaXRlbSk7CiAgICAg
ICAgICB9KTsKICAgICAgfSBlbHNlIGlmICghbmF2aWdhdG9yLnNlbmRCZWFj
b24pIHsKICAgICAgICBjb25zb2xlLmxvZyhgWyR7aXRlbS50eXBlfV0gdXNp
bmcgSW1hZ2UgZmFsbGJhY2sgZm9yIGNsaWNraWQ6ICR7aXRlbS5jbGlja2lk
fWApOwogICAgICAgIG5ldyBJbWFnZSgpLnNyYyA9IHVybDsKICAgICAgfQog
ICAgICBpZiAobmF2aWdhdG9yLnNlbmRCZWFjb24gJiYgc2VudE9LKSB7CiAg
ICAgICAgY29uc29sZS5sb2coYFske2l0ZW0udHlwZX1dIGJlYWNvbiBzdWNj
ZWVkZWQgZm9yIGNsaWNraWQ6ICR7aXRlbS5jbGlja2lkfWApOwogICAgICB9
CiAgICB9KTsKICAgIHNhdmVRdWV1ZShyZW1haW5pbmcpOwogIH0KCiAgLy8g
T24gcGFnZSBsb2FkLCBlbnF1ZXVlIGFuZCBmbHVzaCBQaXRjaCBvbmx5CiAg
ZW5xdWV1ZSgiUGl0Y2giKTsKICBmbHVzaCgpOwoKICAvLyBSZXRyeSBwZW5k
aW5nIG9uIHVubG9hZC92aXNpYmlsaXR5IGNoYW5nZQogIHdpbmRvdy5hZGRF
dmVudExpc3RlbmVyKCd2aXNpYmlsaXR5Y2hhbmdlJywgKCkgPT4gewogICAg
aWYgKGRvY3VtZW50LnZpc2liaWxpdHlTdGF0ZSA9PT0gJ2hpZGRlbicpIGZs
dXNoKCk7CiAgfSk7CiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2JlZm9y
ZXVubG9hZCcsIGZsdXNoKTsKfSkoKTsKPC9zY3JpcHQ+Cg==
`}]},playback:{active:!1,actionAfterFinish:null,disablePause:!1,scrollToActionIn:0,smartPause:!1},playerInit:{aspectRatio:125,thumbnailKey:"b5e8472d-3421-4675-a219-1ae1b636b21f/players/6a14ce977bc2268dcbb4c382/thumbnail.jpg",verticalVideo:!0,customId:null},playerVersion:"v4",preload:"netflix",resume:{active:!0,model:"default",backgroundColor:"#0a1768",disablePause:!1,foregroundColor:"#FFFFFF",play:"Continue watching?",replay:"Start from beginning?",title:"You have already started watching this video"},secure:!1,smartAutoPlay:{active:!0,items:[{id:"smart_autoplay_6a14ce977bc2268dcbb4c382_2_e4588500",autoUnmute:!0,name:"PLAY",number:2,version:"2",startAt:0,endAt:null,animation:{animation:"pulse",properties:{speed:3}},elements:[{height:689.634,id:"6a15a22edc6d158e108c256f",opacity:1,order:1,rotation:0,type:"image",width:689.634,x:195.07629700029702,y:330.07643200043196,transformOrigin:null,properties:{alt:"Smart AutoPlay",src:"https://cdn.converteai.net/b5e8472d-3421-4675-a219-1ae1b636b21f/2024/09/01/66d4ba69507027000167e791.png"}}]}]},style:{background:"#E77E11",bigPlay:!1,borderRadius:0,captions:!1,foreground:"#FFFFFF",forward:!1,fullscreen:!1,progressBar:!1,rewind:!1,smallPlay:!0,speed:!1,videoTime:!1,volume:!1},subtitles:{active:!1},thumbsniper:{active:!1,items:[]},turbo:{active:!1},video:{cover:"https://images.converteai.net/b5e8472d-3421-4675-a219-1ae1b636b21f/players/6a14ce977bc2268dcbb4c382/cover.jpg",startQuality:"auto",id:"6a14ccf1fd96a937a8912e1a",aspectRatio:1.25,height:1350,poster:"https://cdn.converteai.net/b5e8472d-3421-4675-a219-1ae1b636b21f/6a14ccf1fd96a937a8912e1a/poster.jpg",width:1080,drm:!1}}}};e.preloads.netflix=function(n){t.innerHTML=`<div slot="preload" class="preload preload--netflix" style=" position: relative; width: 100%; padding: ${n.playerInit.aspectRatio||56.25}% 0 0; z-index: 0;">`+`<div id="loading_${n.id}" class="vt-loading-wrapper">`+'<div class="vt-loading-android-spinner"></div><div class="vt-loading-percentage">50%</div></div></div>'+`<style>[class^="vt-loading"]{box-sizing:border-box;font-family:Arial,Helvetica,sans-serif;text-decoration:none}.vt-loading-wrapper{position:absolute;top:0;left:0;width:100%;height:100%;z-index:99999;background-color:#000;color:#fff;display:flex!important;justify-content:center;align-items:center}.vt-loading-percentage{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:18px;font-weight:600}#smartplayer .vt-loading-percentage{content:"99%"}.vt-loading-android-spinner{width:80px;aspect-ratio:1;border-radius:50%;background:radial-gradient(farthest-side,#E50914 94%,#0000) top/8px 8px no-repeat,conic-gradient(#0000 30%,#E50914);-webkit-mask:radial-gradient(farthest-side,#0000 calc(100% - 8px),#000 0);animation:vt-loading-android-spinner-animation .75s infinite linear}@keyframes vt-loading-android-spinner-animation{100%{transform:rotate(1turn)}}</style>`;var s,i,o=document.querySelector(".vt-loading-percentage");o&&(s=50,i=setInterval(function(){s++,o.textContent=s+"%",s>=99&&clearInterval(i)},30))},e.preloads.image=function(n){t.innerHTML=`<div class="thumbnail" style="position: relative; width: 100%; padding: ${n.playerInit.aspectRatio||56.25}% 0 0; z-index: 0;">`+`<img class="thumbnail-image" `+`src="https://images.converteai.net/${n.playerInit.thumbnailKey}" `+`style=" position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; display: block;  " />`+`</div>`},e.preload=function(t){if(typeof e.preloads[t.preload]=="function")return e.preloads[t.preload](t);if(typeof e.preloads.netflix=="function")return e.preloads.netflix(t);e.preloads.image(t)},e.loadSmartPlayer=function(t){if(t==="ignore")return;var n,s,o,i,a,r=t;try{s=new URLSearchParams(window.location.search),o=s.get("playerVersion"),o&&(r=o)}catch(e){console.error("Error getting version from search params",e)}if(document.getElementById("vturb-smartplayer-js"))return;n=document.createElement("script"),i="https://scripts.converteai.net/lib/js/smartplayer-wc/"+r;try{a=s.get("playerHost"),a&&(i=decodeURIComponent(a))}catch(e){console.error("error getting playerHost from search params",e)}n.src=i+"/smartplayer.js",n.id="vturb-smartplayer-js",n.fetchPriority="high",document.head.appendChild(n)},e.setupPlayerElement=function(n){if(t.id="vid-"+n.id,!t){t=document.createElement("vturb-smartplayer"),t.id="vid-"+n.id;var s=document.currentScript;s.parentNode.tagName.toLowerCase()==="head"?document.body.insertBefore(t,document.body.firstChild):s.parentNode.insertBefore(t,s)}t.setAttribute("original-id",t.id),n.playerInit.verticalVideo?t.style.maxWidth=window.innerWidth<=450?"100%":"400px":t.style.maxWidth=null,t.style.display="block",t.style.margin="0 auto",t.style.width="100%",t.start=function(n){t.setup?t.setup(n):this._setup=n}},e.checkItem=function(e){return e.config&&e.config.id&&e.config.video},e.anyConfig=function(t){if(e.checkItem(t))return t.config;if(t.children)for(var s,n=0;n<t.children.length;n++)if(s=e.anyConfig(t.children[n]),s)return s;return null},e.validAnyConfig=e.anyConfig(e.config),e.disableNext=!1,e.next=function(t){if(e.disableNext)return;if(t.fn&&e[t.fn]&&t.children)e[t.fn](t.id,t.children,e.next);else if(e.checkItem(t))e.mount(t.config);else throw e.mount(e.validAnyConfig),new Error("No valid config found using next function");return t},e.run=function(){if(!e.validAnyConfig)throw new Error("No valid config found using anyConfig function");try{e.next(e.config)}catch(t){console.error(t),e.mount(e.validAnyConfig)}setTimeout(function(){e.mounted||e.mount(e.validAnyConfig)},3e3)},e.mount=function(n){if(e.mounted){console.warn("Player already mounted");return}e.mounted=!0,e.disableNext=!0,e.preload(n),e.setupPlayerElement(n),e.loadSmartPlayer(n.playerVersion||"v4"),t.start(n)},e.run()}()